name: Daily Stock Data Pipeline

on:
  schedule:
    # Runs at 9 AM UTC from Monday - Friday (10 AM Lagos time)
    - cron: '0 9 * * 1-5'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Run stock pipeline
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
        run: |
          python stock_pipeline.py
      
      - name: Commit and push data
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add stock_data/*.csv
          git commit -m "Update stock data - $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push